const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.NinePatch,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.advert,
		C3.Plugins.CORDOVAIAP,
		C3.Plugins.Text,
		C3.Behaviors.Flash,
		C3.Plugins.Arr,
		C3.Plugins.Json,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Exps.Tags,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Exps.min,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.JavaScriptInEvents.Gamepage_Event33_Act1,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Text.Cnds.PickParent,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Exps.Tags,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Text.Cnds.HasTags,
		C3.Plugins.Text.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{Fill: 0},
	{FillBG: 0},
	{LOADING: 0},
	{LoadingScreenBG: 0},
	{Logo: 0},
	{Tier: 0},
	{Tween: 0},
	{Panels: 0},
	{PopUp_Btn: 0},
	{Close: 0},
	{Click: 0},
	{Buy: 0},
	{Car_: 0},
	{Help: 0},
	{MainPageBG: 0},
	{Active: 0},
	{Play: 0},
	{Audio: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{MobileAdvert: 0},
	{MobileIAP: 0},
	{Circle: 0},
	{LevelSelect: 0},
	{Lock: 0},
	{Clicked: 0},
	{ID: 0},
	{Lvl_Box: 0},
	{Previousbtnarrow: 0},
	{Back: 0},
	{BG: 0},
	{Box: 0},
	{G_Btn: 0},
	{Heart: 0},
	{Hint: 0},
	{Text: 0},
	{oX: 0},
	{oY: 0},
	{Moving: 0},
	{CanMove: 0},
	{Flash: 0},
	{Cars: 0},
	{Array: 0},
	{JSON: 0},
	{LocalStorage: 0},
	{DarkFade: 0},
	{Sine: 0},
	{Faild: 0},
	{Flar: 0},
	{GamePage_Btn: 0},
	{LevelComplete: 0},
	{Lvl_Box_Holder: 0},
	{Panel: 0},
	{Paused: 0},
	{ShiningEffect: 0},
	{CornerDecoration: 0},
	{GradientFade: 0},
	{Sound: 0},
	{Current_Lvl: 0},
	{Unlocked_Lvl: 0},
	{Lvl_Page: 0}
];

self.InstanceType = {
	Fill: class extends self.I9PatchInstance {},
	FillBG: class extends self.ISpriteInstance {},
	LOADING: class extends self.ISpriteInstance {},
	LoadingScreenBG: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	Tier: class extends self.ISpriteInstance {},
	Panels: class extends self.ISpriteInstance {},
	PopUp_Btn: class extends self.ISpriteInstance {},
	Close: class extends self.ISpriteInstance {},
	Buy: class extends self.ISpriteInstance {},
	Car_: class extends self.ISpriteInstance {},
	Help: class extends self.ISpriteInstance {},
	MainPageBG: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	MobileAdvert: class extends self.IInstance {},
	MobileIAP: class extends self.IInstance {},
	Circle: class extends self.ISpriteInstance {},
	LevelSelect: class extends self.ISpriteInstance {},
	Lvl_Box: class extends self.ISpriteInstance {},
	Previousbtnarrow: class extends self.ISpriteInstance {},
	Back: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	Box: class extends self.ISpriteInstance {},
	G_Btn: class extends self.ISpriteInstance {},
	Heart: class extends self.ISpriteInstance {},
	Hint: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Cars: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	JSON: class extends self.IJSONInstance {},
	LocalStorage: class extends self.IInstance {},
	DarkFade: class extends self.ISpriteInstance {},
	Faild: class extends self.ISpriteInstance {},
	Flar: class extends self.ISpriteInstance {},
	GamePage_Btn: class extends self.ISpriteInstance {},
	LevelComplete: class extends self.ISpriteInstance {},
	Lvl_Box_Holder: class extends self.ISpriteInstance {},
	Panel: class extends self.ISpriteInstance {},
	Paused: class extends self.ISpriteInstance {},
	ShiningEffect: class extends self.ISpriteInstance {},
	CornerDecoration: class extends self.ISpriteInstance {},
	GradientFade: class extends self.ISpriteInstance {}
}